version: 2.1

orbs:
  xmatters: xmatters/xmatters-orb@1.0.4

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
    
    request-approval:
      docker:
        - image: circleci/node:4.8.2
      steps:
        - xmatters/notify:
            recipients: Engineering Managers
    
workflows:
  build-test-and-approval-deploy:
    jobs:
      - build
      - request-approval
      hold:
        type: approval
        requires: 
          - build
          - request-approval
      deploy-stuff:
        requires:
          - hold